Repository Team-Catxi/Catxi_FrontEnd, pull requests merged in 2025-05, with the labels that each got.

#4 Setting: main
  .github/ISSUE_TEMPLATE/blank-issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: setting

#9 feat: common-layout
  CATXI-FE/index.html
  CATXI-FE/package.json
  CATXI-FE/pnpm-lock.yaml
  CATXI-FE/src/App.css
  CATXI-FE/src/App.tsx
  CATXI-FE/src/components/Common/CommonCard.tsx
  CATXI-FE/src/index.css
  CATXI-FE/src/layouts/HomeLayout.tsx
  CATXI-FE/src/main.tsx
  CATXI-FE/src/pages/ChatPage.tsx
  CATXI-FE/src/pages/Error/index.tsx
  CATXI-FE/src/pages/HomePage.tsx
  CATXI-FE/tailwind.config.js
  CATXI-FE/tsconfig.app.json
  CATXI-FE/vite.config.ts
Labels: feat, invalid, setting

#16 setting/test
  CATXI-FE/public/icon.png
  CATXI-FE/public/icon2.png
  CATXI-FE/public/icon3.png
  CATXI-FE/vite.config.ts
Labels: fix, invalid

#17 chore/setting
  CATXI-FE/index.html
  CATXI-FE/tailwind.config.js
  CATXI-FE/tailwind.config.ts
Labels: setting

#22 feat: signIn-UI
  CATXI-FE/src/assets/icons/close.svg
  CATXI-FE/src/pages/Login/index.tsx
  CATXI-FE/src/pages/SiginIn/index.tsx
Labels: feat

#24 feat: createChat-UI
  CATXI-FE/src/App.tsx
  CATXI-FE/src/assets/icons/arrow.svg
  CATXI-FE/src/assets/icons/increase.svg
  CATXI-FE/src/assets/icons/info.svg
  CATXI-FE/src/assets/icons/reduce.svg
  CATXI-FE/src/pages/CreateChat/_components/AllSet.tsx
  CATXI-FE/src/pages/CreateChat/_components/PlaceToggleBtn.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectMembers.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectPlace.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectTime.tsx
  CATXI-FE/src/pages/CreateChat/_components/TimePicker.tsx
  CATXI-FE/src/pages/CreateChat/_components/TimeToggleBtn.tsx
  CATXI-FE/src/pages/CreateChat/_constants/place.ts
  CATXI-FE/src/pages/CreateChat/index.tsx
Labels: feat

#27 feat: myPage-UI
  CATXI-FE/src/App.tsx
  CATXI-FE/src/assets/icons/cardClose.svg
  CATXI-FE/src/pages/MyPage/_components/RecordCard.tsx
  CATXI-FE/src/pages/MyPage/index.tsx
Labels: feat

#29 fix: 경로 오타 수정
  CATXI-FE/src/pages/MyPage/index.tsx
Labels: fix

#31 fix/login-UI
  CATXI-FE/src/assets/icons/kakao.svg
  CATXI-FE/src/assets/icons/loginCheck.svg
  CATXI-FE/src/pages/Login/index.tsx
  CATXI-FE/src/pages/SiginIn/index.tsx
Labels: fix

#32 Feat: home
  CATXI-FE/src/App.tsx
  CATXI-FE/src/pages/Home/_components/CategoryTab.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/ChatJoinButton.tsx
  CATXI-FE/src/pages/Home/_components/FloatingButton.tsx
  CATXI-FE/src/pages/Home/_components/LocationFilter.tsx
  CATXI-FE/src/pages/Home/index.tsx
  CATXI-FE/src/pages/HomePage.tsx
Labels: fix, feat, style

#36 fix/navigate-createChat
  CATXI-FE/src/assets/icons/Float.svg
  CATXI-FE/src/pages/Home/_components/FloatingButton.tsx
Labels: fix

#37 Feat/tab bar
  CATXI-FE/src/assets/icons/ChatButton.svg
  CATXI-FE/src/assets/icons/ChatIcon.svg
  CATXI-FE/src/assets/icons/HomeButton.svg
  CATXI-FE/src/assets/icons/HomeIcon.svg
  CATXI-FE/src/assets/icons/MyButton.svg
  CATXI-FE/src/assets/icons/MyIcon.svg
  CATXI-FE/src/components/Tab/TabBar.tsx
  CATXI-FE/src/layouts/HomeLayout.tsx
  CATXI-FE/src/pages/Chat/_components/ChatInput.tsx
  CATXI-FE/src/pages/Home/_components/CategoryTab.tsx
  CATXI-FE/src/pages/Home/_components/FloatingButton.tsx
  CATXI-FE/src/pages/Home/_components/LocationFilter.tsx
  CATXI-FE/src/pages/Home/index.tsx
Labels: feat, style

#38 chore/icon
  CATXI-FE/src/assets/icons/ChatButton.svg
Labels: fix
