Repository Team-Catxi/Catxi_FrontEnd, pull requests merged in 2025-06, with the labels that each got.

#44 feat/server-test
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/utils/chatUtils.ts
Labels: feat

#46 feat/createChat-scrollPicker
  CATXI-FE/package.json
  CATXI-FE/pnpm-lock.yaml
  CATXI-FE/src/index.css
  CATXI-FE/src/pages/CreateChat/_components/AllSet.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectTime.tsx
  CATXI-FE/src/pages/CreateChat/_components/TimePicker.tsx
  CATXI-FE/src/pages/CreateChat/index.tsx
  CATXI-FE/src/types/react-mobile-picker-scroll.d.ts
Labels: feat

#48 Fix: chat-test-webSocket
  CATXI-FE/src/assets/icons/PushButton.svg
  CATXI-FE/src/components/Modal/UserModal.tsx
  CATXI-FE/src/contexts/ModalContext.tsx
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/index.css
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/layouts/HomeLayout.tsx
  CATXI-FE/src/pages/Chat/_components/ChatBoard.tsx
  CATXI-FE/src/pages/Chat/_components/ChatInput.tsx
  CATXI-FE/src/pages/Chat/_components/ChatItem.tsx
  CATXI-FE/src/pages/Chat/_components/ChatList.tsx
  CATXI-FE/src/utils/chatUtils.ts
Labels: fix, feat, invalid, refactor

#50 Fix: chat-websocket
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/utils/chatUtils.ts
Labels: fix

#52 chore/addLogo
  CATXI-FE/index.html
  CATXI-FE/public/logo.svg
  CATXI-FE/src/assets/icons/logoText.svg
  CATXI-FE/src/pages/Login/index.tsx
Labels: style

#54 Fix: chat-history
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/apis/chat.ts
  CATXI-FE/src/hooks/query/useChatMessages.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/types/chatHistory.ts
  CATXI-FE/src/utils/chatUtils.ts
Labels: fix, api, feat

#58 api/login
  CATXI-FE/src/App.tsx
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/components/Tab/TabBar.tsx
  CATXI-FE/src/pages/Login/index.tsx
  CATXI-FE/src/pages/Redirect/index.tsx
  CATXI-FE/src/types/login.ts
  CATXI-FE/src/utils/authCheck.ts
  CATXI-FE/src/utils/crypto.ts
  CATXI-FE/src/utils/storage.ts
Labels: api

#55 API: get chat-rooms
  CATXI-FE/src/apis/chat.ts
  CATXI-FE/src/apis/chatRooms.ts
  CATXI-FE/src/hooks/query/useChatMessages.ts
  CATXI-FE/src/hooks/query/useChatRooms.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/pages/Home/_components/CategoryTab.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/ChatJoinButton.tsx
  CATXI-FE/src/pages/Home/_components/LocationFilter.tsx
  CATXI-FE/src/pages/Home/index.tsx
  CATXI-FE/src/types/apiResponse.ts
  CATXI-FE/src/types/chatData.ts
  CATXI-FE/src/types/chatHistory.ts
Labels: fix, api, feat, style

#62 Fix: Chat-WebSocket
  CATXI-FE/package.json
  CATXI-FE/pnpm-lock.yaml
  CATXI-FE/src/apis/chatRooms.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/pages/Chat/_components/ChatBoard.tsx
  CATXI-FE/src/pages/Chat/_components/ChatItem.tsx
  CATXI-FE/src/pages/Chat/_components/ChatList.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/FloatingButton.tsx
  CATXI-FE/src/types/chatData.ts
  CATXI-FE/src/types/stomp.d.ts
  CATXI-FE/src/utils/test/getMemberInfo.ts
Labels: fix, invalid

#63 chore/axios
  CATXI-FE/src/App.tsx
  CATXI-FE/src/apis/axios.ts
Labels: fix

#66 api/login-fix
  CATXI-FE/src/apis/signIn.ts
  CATXI-FE/src/hooks/useSignIn.ts
  CATXI-FE/src/pages/Redirect/index.tsx
  CATXI-FE/src/pages/SiginIn/index.tsx
  CATXI-FE/src/types/signIn.ts
Labels: api, feat

#67 feat/myPage-api
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/apis/history.ts
  CATXI-FE/src/apis/myPage.ts
  CATXI-FE/src/hooks/query/useMyPage.ts
  CATXI-FE/src/pages/MyPage/_components/RecordCard.tsx
  CATXI-FE/src/pages/MyPage/_utils/location.ts
  CATXI-FE/src/pages/MyPage/index.tsx
  CATXI-FE/src/types/history.ts
  CATXI-FE/src/types/myPage.ts
Labels: api, feat

#70 api/createChat
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/apis/createChat.ts
  CATXI-FE/src/hooks/mutation/sse/useCreateChat.ts
  CATXI-FE/src/pages/CreateChat/_components/AllSet.tsx
  CATXI-FE/src/pages/CreateChat/_components/PlaceToggleBtn.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectMembers.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectPlace.tsx
  CATXI-FE/src/pages/CreateChat/_components/SelectTime.tsx
  CATXI-FE/src/pages/CreateChat/_components/TimePicker.tsx
  CATXI-FE/src/pages/CreateChat/_constants/answer.ts
  CATXI-FE/src/pages/CreateChat/_constants/place.ts
  CATXI-FE/src/pages/CreateChat/_constants/time.ts
  CATXI-FE/src/pages/CreateChat/index.tsx
  CATXI-FE/src/pages/MyPage/_utils/location.ts
  CATXI-FE/src/store/createChatStore.ts
  CATXI-FE/src/types/createChat.ts
Labels: api, feat, refactor

#74 chore/logo
  CATXI-FE/public/logo.svg
  CATXI-FE/src/assets/icons/logoText.svg
  CATXI-FE/src/pages/Login/index.tsx
Labels: style

#76 api/deleteUser
  CATXI-FE/src/apis/deleteUser.ts
  CATXI-FE/src/hooks/mutation/sse/useDeleteUser.ts
  CATXI-FE/src/pages/MyPage/index.tsx
Labels: api, feat

#69 Feat: sse
  CATXI-FE/src/apis/chatRooms.ts
  CATXI-FE/src/constants/stationMap.ts
  CATXI-FE/src/hooks/mutation/chat/useJoinChatRoom.ts
  CATXI-FE/src/hooks/query/useChatRooms.ts
  CATXI-FE/src/pages/Chat/_components/DepartureInfoBox.tsx
  CATXI-FE/src/pages/Home/_components/CategoryTab.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/ChatJoinButton.tsx
  CATXI-FE/src/pages/Home/_components/FloatingButton.tsx
  CATXI-FE/src/pages/Home/_components/LocationFilter.tsx
  CATXI-FE/src/pages/Home/index.tsx
  CATXI-FE/src/types/chat.ts
  CATXI-FE/src/types/chatData.ts
  CATXI-FE/src/utils/date.ts
Labels: api, feat

#86 Chore: home-chatlist
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/ChatJoinButton.tsx
  CATXI-FE/src/pages/Home/_components/LocationFilter.tsx
  CATXI-FE/src/pages/Home/index.tsx
  CATXI-FE/src/types/chatData.ts
  CATXI-FE/src/utils/date.ts
Labels: fix, style

#93 Fix: chat-socket
  CATXI-FE/src/hooks/useChatConnection.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/types/chat.ts
Labels: fix

#94 Api/chat delete
  CATXI-FE/src/App.tsx
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/apis/chat/chat.ts
  CATXI-FE/src/apis/chat/chatRequest.ts
  CATXI-FE/src/apis/chat/chatRooms.ts
  CATXI-FE/src/apis/chat/chatStatus.ts
  CATXI-FE/src/components/Tab/TabBar.tsx
  CATXI-FE/src/hooks/mutation/chat/useJoinChatRoom.ts
  CATXI-FE/src/hooks/mutation/chat/useReadyQuest.ts
  CATXI-FE/src/hooks/query/useChatMessages.ts
  CATXI-FE/src/hooks/query/useChatRoomId.ts
  CATXI-FE/src/hooks/query/useChatRooms.ts
  CATXI-FE/src/hooks/useChatConnection.ts
  CATXI-FE/src/layouts/GlobalErrorPage.tsx
  CATXI-FE/src/pages/Chat/_components/ChatList.tsx
  CATXI-FE/src/types/chat.ts
Labels: fix, api, feat

#96 Fix/chat-components
  CATXI-FE/src/apis/axios.ts
  CATXI-FE/src/apis/chat/chat.ts
  CATXI-FE/src/apis/chat/chatDetail.ts
  CATXI-FE/src/apis/chat/chatRequest.ts
  CATXI-FE/src/apis/chat/chatRooms.ts
  CATXI-FE/src/assets/icons/Timer.svg
  CATXI-FE/src/components/Modal/LeaveRoomModal.tsx
  CATXI-FE/src/components/Modal/ReportModal.tsx
  CATXI-FE/src/components/Modal/UserModal.tsx
  CATXI-FE/src/contexts/ModalContext.tsx
  CATXI-FE/src/hooks/mutation/chat/useReadyQuest.ts
  CATXI-FE/src/hooks/query/useChatDetail.ts
  CATXI-FE/src/hooks/query/useChatMessages.ts
  CATXI-FE/src/hooks/query/useChatRoomId.ts
  CATXI-FE/src/hooks/query/useChatRooms.ts
  CATXI-FE/src/hooks/useChatConnection.ts
  CATXI-FE/src/hooks/useChatSocket.ts
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/pages/Chat/_components/ChatBoard.tsx
  CATXI-FE/src/pages/Chat/_components/ChatItem.tsx
  CATXI-FE/src/pages/Chat/_components/ChatList.tsx
  CATXI-FE/src/pages/Chat/_components/DepartureInfoBox.tsx
  CATXI-FE/src/pages/Chat/_components/Info/DefaultBox.tsx
  CATXI-FE/src/pages/Chat/_components/Info/ReadyLockedBox.tsx
  CATXI-FE/src/pages/Chat/_components/JoinMessage.tsx
  CATXI-FE/src/pages/Chat/_components/SystemMessage.tsx
  CATXI-FE/src/pages/Chat/_components/TopStatusBar.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/pages/Home/_components/ChatCardList.tsx
  CATXI-FE/src/pages/Home/_components/ChatJoinButton.tsx
  CATXI-FE/src/types/chat/chat.ts
  CATXI-FE/src/types/chat/chatData.ts
  CATXI-FE/src/types/chat/chatRoomDetail.ts
  CATXI-FE/src/utils/chat/chatSocketUtils.ts
Labels: fix, api, feat, style

#100 Fix: chat members
  CATXI-FE/src/pages/Chat/_components/Info/DefaultBox.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
Labels: fix

#122 bug/signIn
  CATXI-FE/src/pages/Redirect/index.tsx
Labels: fix

#128 Refactor: matched-timer
  CATXI-FE/src/pages/Chat/_components/Info/ReadyLockedBox.tsx
Labels: refactor

#133 fix/websocket
  CATXI-FE/src/components/Modal/ReadyRequestModal.tsx
  CATXI-FE/src/hooks/mutation/chat/useReadyQuest.ts
  CATXI-FE/src/hooks/useChatConnection.tsx
  CATXI-FE/src/layouts/ChatLayout.tsx
  CATXI-FE/src/pages/Chat/_components/DepartureInfoBox.tsx
Labels: fix

#136 Chore: Css
  CATXI-FE/src/pages/Chat/_components/ChatBoard.tsx
  CATXI-FE/src/pages/Chat/_components/ChatItem.tsx
  CATXI-FE/src/pages/Chat/_components/ChatList.tsx
  CATXI-FE/src/pages/Chat/index.tsx
  CATXI-FE/src/pages/Home/_components/ChatCard.tsx
  CATXI-FE/src/utils/date.ts
Labels: style
